env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
extends: eslint:recommended
rules:
  eol-last: 2
  no-cond-assign: 0
  no-multiple-empty-lines: [2, {max: 2, maxEOF: 1}]
  no-trailing-spaces: 2
  space-after-keywords: 2
  semi: 2
  quotes: [2, single, avoid-escape]
