language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 12
  - 10
  - 8
services:
  - couchdb
env:
  - REST_ON_COUCH_USERNAME=admin REST_ON_COUCH_PASSWORD=admin
before_script:
  - sh setupDatabase.sh
after_script: 'bash <(curl -s https://codecov.io/bash)'
