language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 9
  - 8
sudo: false
services:
  - couchdb
env:
  - REST_ON_COUCH_USERNAME=admin REST_ON_COUCH_PASSWORD=admin
  - DEBUG=couch:*
before_script:
  - sh setupDatabase.sh