version: '3'
services:
  db:
    image: couchdb:2.3
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - 127.0.0.1:5984:5984
  ldap:
    build: ./ldap
    ports:
      - 389:389
