version: '3'
services:
  db:
    image: couchdb:1.7.0
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - 127.0.0.1:5984:5984
    volumes:
      - ./couch-test:/usr/local/var/lib/couchdb
