env:
  browser: true

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - react

rules:
  react/jsx-curly-spacing: error
  react/jsx-equals-spacing: error
  react/jsx-space-before-closing: error
  react/jsx-tag-spacing: error
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
