name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      couchdb:
        image: couchdb:latest
        env:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: admin
        ports:
          - 5984:5984
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup test database
        run: bash setupDatabase.sh
      - name: npm install and test
        env:
          REST_ON_COUCH_USERNAME: admin
          REST_ON_COUCH_PASSWORD: admin
        run: |
          npm ci
          npm test
