name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: 16.x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run eslint
      - name: Run Prettier
        run: npm run prettier
  test:
    runs-on: ubuntu-latest
    services:
      couchdb:
        image: couchdb:latest
        env:
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: admin
        ports:
          - 5984:5984
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup test database
        run: bash setupDatabase.sh
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        env:
          REST_ON_COUCH_USERNAME: admin
          REST_ON_COUCH_PASSWORD: admin
        run: npm test
