name: Node.js Package
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      couchdb:
        image: couchdb:latest
        ports:
          - 5984:5984
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup test database
        run: sh setupDatabase.sh
      - name: npm install and test
        env:
          REST_ON_COUCH_USERNAME: admin
          REST_ON_COUCH_PASSWORD: admin
        run: |
          npm ci
          npm test
      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
